[project]
copyright = "Copyright &copy; 2025 Eran Rivlis"
site_name = "MappingTools"
site_author = "Eran Rivlis"
site_description = ""
repo_url = "https://erivlis.github.io/mappingtools/"
repo_name = "erivlis/mappingtools"

#license = "https://github.com/erivlis/mappingtools/LICENSE"
extra_css = [
    "stylesheets/extra.css"
]
nav = [
    { Start = [
        "index.md",
        "installation.md",
        "overview.md"
    ] },
    { Examples = [
        "examples/collectors.md",
        "examples/operators.md",
        "examples/structures.md",
        "examples/transformers.md"
    ] },
    { Development = [
        "design_decisions.md",
        "development_guide.md",
        "contributing.md",
        "acknowledgements.md"
    ] }
]


[project.theme]
variant = "classic"
font.text = "Inter"
font.code = "JetBrains Mono"
language = "en"
logo = "images/logo.png"
favicon = "images/logo.png"
features = [
    "content.code.copy",
    "content.code.select",
    "navigation.footer",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.sections",
#    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "toc.follow",
]


#[project.extra]
#social = [
#    { icon = "fontawesome/brands/github", link = "https://github.com/erivlis/mappingtools" },
#    { icon = "fontawesome/brands/x-twitter", link = "https://x.com/erivlis" },
#    { icon = "fontawesome/solid/envelope", link = "mailto:eran@rivlis.info" },
#    { icon = "fontawesome/solid/mastodon", link = "https://mastodon.social/@erivlis" }
#]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/erivlis"
[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://x.com/erivlis"
[[project.extra.social]]
icon = "fontawesome/brands/mastodon"
link = "https://mastodon.social/@erivlis"
[[project.extra.social]]
icon = "fontawesome/brands/bluesky"
link = "https://bsky.app/@erivlis"
[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/eranrivlis/"
[[project.extra.social]]
icon = "fontawesome/solid/at"
link = "mailto:eran@rivlis.info"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_source = false


[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji" # (1)!
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.toc]
permalink = true
toc_depth = 3
